"""
Shared Pipeline State — AgentState TypedDict
============================================
Defines the single mutable state object that flows through every node
of the LangGraph StateGraph. All 8 agents read from and write to this dict.

LangGraph passes a copy of the state into each node function, and merges
the returned state back into the graph. Fields not modified by a node are
preserved unchanged (partial-update semantics).

Field lifecycle:
  Query Phase  (Supervisor + Preference):  query, complexity, selected_llm,
                                            category, budget, intent_preferences,
                                            priority_vector
  Data Phase   (Retrieval + Enrichment):   retrieved_products, enriched_products
  Score Phase  (Comparison):               scored_products
  Audit Phase  (Critique):                 critique_passed, critique_feedback,
                                            revision_count
  Output Phase (Recommendation):           final_recommendation
  Memory Phase (Learning):                 writes to user_memory.json externally
"""
from typing import TypedDict, List, Dict, Any, Optional


class AgentState(TypedDict):
    """
    Shared mutable state passed through every LangGraph agent node.

    All agents use state.get(key, default) to safely read fields.
    """

    # ── Query Metadata ────────────────────────────────────────────────────────
    query: str
    """Raw natural-language query from the user."""

    complexity: str
    """'simple' or 'complex' — set by Supervisor, used for LLM routing."""

    selected_llm: str
    """'local' (Ollama/MockLLM) or 'premium' (Gemini) — set by Supervisor."""

    # ── Parsed Intent ─────────────────────────────────────────────────────────
    category: str
    """Canonical product category (laptop, smartphone, headphones, …)."""

    budget: Dict[str, Optional[float]]
    """{'min': float|None, 'max': float|None} extracted from the query."""

    intent_preferences: List[str]
    """Feature keywords extracted from the query (e.g. 'long battery', 'lightweight')."""

    priority_vector: Dict[str, float]
    """5-axis weight vector {price, performance, brand, durability, innovation}.
    Values sum to ~1.0. Used by Comparison Agent for weighted scoring."""

    # ── Product Data Pipeline ─────────────────────────────────────────────────
    retrieved_products: List[Dict[str, Any]]
    """Raw product records from FAISS semantic search + optional RapidAPI boost."""

    enriched_products: List[Dict[str, Any]]
    """Products after Enrichment fills missing specs and infers value tiers."""

    scored_products: List[Dict[str, Any]]
    """Products ranked by Comparison Agent; includes overall_score, criteria_scores,
    and is_pareto_optimal flag. Sorted descending by overall_score."""

    # ── Quality Control ───────────────────────────────────────────────────────
    critique_passed: bool
    """True if Critique Agent validated outputs; False triggers a retry loop."""

    critique_feedback: str
    """Explanation from Critique Agent when validation fails."""

    revision_count: int
    """Number of critique retry loops completed. Hard cap: 2 (see graph.py)."""

    # ── Output ────────────────────────────────────────────────────────────────
    final_recommendation: str
    """Markdown advisory report generated by the Recommendation Agent."""

    error: Optional[str]
    """Set if a catastrophic error occurred; downstream agents should check."""

    history: List[Any]
    """LangChain message history (reserved for multi-turn conversation)."""
